//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod junction;
pub mod sample_a;
pub mod sample_b;
pub mod sample_c;
pub mod sample_d;
pub mod sample_e;
pub mod sample_f;
