//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::junction::Entity as Junction;
pub use super::sample_a::Entity as SampleA;
pub use super::sample_b::Entity as SampleB;
pub use super::sample_c::Entity as SampleC;
pub use super::sample_d::Entity as SampleD;
pub use super::sample_e::Entity as SampleE;
pub use super::sample_f::Entity as SampleF;
