//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sample_c")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sample_d::Entity")]
    SampleD,
}

impl Related<super::sample_d::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SampleD.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
