//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sample_d")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub value: String,
    pub sample_c_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sample_c::Entity",
        from = "Column::SampleCId",
        to = "super::sample_c::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SampleC,
}

impl Related<super::sample_c::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SampleC.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
